// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvgydcelsxkfxyttibqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2Z3lkY2Vsc3hrZnh5dHRpYnFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NTc4NDUsImV4cCI6MjA2MTEzMzg0NX0.ii7ABrlRi8TEgq2NA_s4O0wDZf59QDhV7GjbUSdu1F4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);